### ISSUE TITLE
Validate also post method, setup in annotation?

### ISSUE THREAD

**Issue by ghost** [Genedys/csrf-route-bundle#2]
I use `@CsrfToken` in my controller route definition, this validate get method, can I set there also post method validation?

**Comment by fantoine** [comment]
If you want to use CSRF tokens on POST methods I advise you to use Symfony forms.

This library is useful when you want to have CSRF tokens but can't have forms (eg: GET actions).

**Comment by ghost** [comment]
It means I cannot validate POST method? Only GET?

If I edit model/CsrfToken.php getMethods() to `return array('GET', 'POST');` then it works... so I think it is only to setup in annotation?

**Comment by enumag** [comment]
It should be possible to validate POST as well, we just never really tried since it's not the recommended way. Try and see for yourself.

**Comment by fantoine** [comment]
In fact you can specify multiple HTTP methods.
There is a `methods` option for `@CsrfToken` annotation where you can specify HTTP methods to support through an array.

However, since we use query parameters to extract CSRF informations, I definitly advise you to use Symfony forms for POST methods.
